### ISSUE TITLE
[BUG] Island Centering w/ World Edit

### ISSUE THREAD

**Issue by OffCourseYT** [IridiumLLC/IridiumSkyblock#278]
**Describe the bug**
My island schematic does not center when world edit is in the server.

**To Reproduce**
1. Create an island using this schem with world edit (World Edit Version6.1.7) active: http://www.mediafire.com/file/wre0bh4zs64ihn9/island.schematic/file
2. Island wont be inside the border.

**Screenshots**
https://prnt.sc/utmzmx

**Comment by ImBas** [comment]
This bug seems to happen for any WorldEdit versions under 7.0.0 (so any pre- 1.13 version).
Here's a short recording I made demonstrating the issue, which may help: https://streamable.com/faprau

I feel like the pre 7.0.0 WorldEdit versions are attempting to paste the schematics taking one of the bottom corner points as center of the skyblock area, instead of the actual center of the schematic (if that makes sense).

**Comment by ImBas** [comment]
Any update on this issue? @IridiumLLC 
We're waiting for a fix before we are able to deploy this on all of our networks.
