### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Togalkan** [IridiumLLC/IridiumSkyblock#296]
The / is shop no longer works to sell but to buy it still works in the latest version

**Comment by Togalkan** [comment]
Can't shoot with the bow

**Comment by Togalkan** [comment]
Thank you for your reply

**Comment by Sidpatchy** [comment]
I'll make an actual bug report since this brainlet didn't and instead removed the whole template. 

**Describe the bug**
The island shop no longer allows players to sell items. Players are still able to purchase items.

**To Reproduce**
Steps to reproduce the behavior:
1. Obtain an item to sell
2. type "/is shop" in the chat
3. Locate item in shop and attempt to sell

Error printed in console: https://pastebin.com/EprZhNQ9

**Comment by IridiumLLC** [comment]
Das fixed this issue already, Update will be out tomorrow :)

**Comment by IridiumLLC** [comment]
p.s. this goes to show that following the template helps alot, since I had no clue what the first guy was on about xD
