### ISSUE TITLE
[BUG] Island Level

### ISSUE THREAD

**Issue by EatRamen1** [IridiumLLC/IridiumSkyblock#332]
Whenever I recalculate the island level it changes drastically, like it goes up and then back down then up again till it reaches some sort of balance which I think is the correct Island Level. It just seems to be fluctuating a lot for the players that aren't even on & I know that blocks aren't being placed or removed.

**Comment by MertUnverdi** [comment]
Please expalin it with Screenshots etc.

**Comment by IridiumLLC** [comment]
Could you please follow the correct format?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Console Error**
If applicable, a pastebin link of any console errors

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by MertUnverdi** [comment]
didn't answered..
