### ISSUE TITLE
SignShop plugin issue

### ISSUE THREAD

**Issue by TheTheSzef** [IridiumLLC/IridiumSkyblock#353]
Players can't use shop signs without permission "interact" which allows them to open chests ;/
(SignShop plugin)

**Comment by IridiumLLC** [comment]
Sounds like an issue with the SignShops developer

**Comment by weaves7** [comment]
Hi I am the current developer of SignShop. I don't think that TheTheSzef was clear with what the issue is. When someone clicks on a shop sign Iridium cancels the event unless the player is in a group that has the "interact" permission. SignShop respects protection plugins by not running the shop code if the event is canceled. Neither plugin is at fault here it is just two conflicting designs. My question is would you be willing to separate the "interact" permission into multiple permissions? This would benefit your users as well as mine since they would have more control over what happens on their island and be able to use shops. For example a player may want visitors to be able to click signs and open wooden doors but not be able to use levers, buttons, or flint and steel or open chests. Currently it is all or nothing, unless we are missing something.
