### ISSUE TITLE
[BUG] Place Water and Lava without permission

### ISSUE THREAD

**Issue by 0VERR** [IridiumLLC/IridiumSkyblock#370]
When players have a bucket of lava or water in their hands and click on a block on another player's island, water or lava will appear even if they have no permissions on that island,

No console error

Screenshot: https://imgur.com/a/J5EapdA

**Comment by MertUnverdi** [comment]
Could you please follow the correct format?

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Console Error
If applicable, a pastebin link of any console errors

Screenshots
If applicable, add screenshots to help explain your problem.

**Comment by 0VERR** [comment]
When players have a bucket of lava or water in their hands and click on a block on another player's island, water or lava will appear even if they have no permissions on that island, 

No console error

Screenshot: https://imgur.com/a/J5EapdA
